name: mir-kiosk-scummvm
adopt-info: scummvm
summary: ScummVM packaged as a mir-kiosk snap
description: ScummVM packaged as a mir-kiosk snap
confinement: strict
grade: stable
base: core18
license: GPL-2.0

environment:
  SHELL: bash
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  # Prep EGL
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  # Prep SDL
  SDL_VIDEODRIVER: wayland

layout:
  /usr/share:
    bind: $SNAP/usr/share
  /etc/glvnd:
    bind: $SNAP/etc/glvnd
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/games:
    bind: $SNAP/usr/games

plugs:
  wayland:
  opengl:
  pulseaudio:
  alsa:

apps:
  daemon:
    command: run-daemon wayland-launch scummvm-launch
    daemon: simple
    restart-condition: on-failure
    environment:
      # Prep PulseAudio
      PULSE_SYSTEM: 1
      PULSE_RUNTIME_PATH: /var/run/pulse

  mir-kiosk-scummvm:
    command: wayland-launch scummvm-launch
    desktop: usr/share/applications/scummvm.desktop
    environment:
      # Prep PulseAudio
      PULSE_SERVER: unix:$XDG_RUNTIME_DIR/../pulse/native

parts:
  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  glue:
    plugin: dump
    source: glue

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl pulseaudio alsa wayland

  scummvm:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `LANG=C apt-cache policy scummvm | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    stage-packages:
      - scummvm
      - fluidsynth
      - timidity
      - beneath-a-steel-sky
#      - drascula "WARNING: Incorrect version of the 'drascula.dat' engine data file found. Expected 5.0 but got 4.0.!"
      - flight-of-the-amazon-queen
      - lure-of-the-temptress
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0

  drascula:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/universe/d/drascula/drascula_1.0+ds3-1_all.deb

  mesa:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libwayland-egl1-mesa
      - libglu1-mesa

  misc:
    plugin: nil
    stage-packages:
      - libwayland-client0
      - libpulse0
      - libsndfile1
      - libasyncns0